### ISSUE TITLE
Any side-effects from removing test.pdf?

### ISSUE THREAD

**Issue by mryellow** [MomsFriendlyDevCo/pdf-dicer#6]
https://github.com/MomsFriendlyDevCo/pdf-dicer/blob/ae22faf3af311b40d3f3c4536d40e7168966b415/index.js#L348

**Comment by hash-bang** [comment]
I doubt it. It looks like a debug artefact.

Want me to nuke it or you ok doing it? You have write access.

**Comment by hash-bang** [comment]
Actually forget it. Easier if I get off my lazy ass. Fixed in `0.4.1`
